import { strict as assert } from "node:assert";
import { describe, it } from "mocha";
import { buildReviewMarkdown } from "../../src/panels/reviewMarkdown";
import { markdownToHtml } from "../../src/panels/markdownToHtml";
import type { DiffResult } from "../../src/ipc/types";

function makeDiff(p: Partial<DiffResult> = {}): DiffResult {
  return {
    base_ref: "HEAD",
    changed_files: [],
    total_reachable: 0,
    total_confidence_weighted: 0,
    inconsistencies_introduced: [],
    new_orphans: [],
    git_operation_in_progress: false,
    ...p,
  };
}

describe("reviewMarkdown – buildReviewMarkdown", () => {
  it("emits the heading + table + 'no symbols touched' when empty", () => {
    const md = buildReviewMarkdown(makeDiff());
    assert.match(md, /## CoreGraph impact analysis/);
    assert.match(md, /\| Changed files \| \*\*0\*\* \|/);
    assert.match(md, /No symbols touched/);
  });

  it("renders touched symbol bullets per changed file", () => {
    const md = buildReviewMarkdown(
      makeDiff({
        changed_files: [
          {
            file: "/proj/a.rs",
            seed_symbols: ["foo", "bar"],
            reachable_count: 2,
            confidence_weighted: 1.5,
            top_affected: [],
          },
        ],
        total_reachable: 2,
        total_confidence_weighted: 1.5,
      }),
    );
    assert.match(md, /\| Touched symbols \| \*\*2\*\* \|/);
    assert.match(md, /- `foo` — `\/proj\/a\.rs`/);
    assert.match(md, /- `bar` — `\/proj\/a\.rs`/);
  });

  it("truncates touched list beyond 25 with a '…and N more' line", () => {
    const seed_symbols = Array.from({ length: 30 }, (_, idx) => `s${idx}`);
    const md = buildReviewMarkdown(
      makeDiff({
        changed_files: [{
          file: "/f",
          seed_symbols,
          reachable_count: 30,
          confidence_weighted: 0,
          top_affected: [],
        }],
      }),
    );
    assert.match(md, /…and 5 more/);
    assert.ok(md.includes("- `s24`"));
    assert.ok(!md.includes("- `s25`"));
  });

  it("includes the generator footer", () => {
    const md = buildReviewMarkdown(makeDiff());
    assert.match(md, /<sub>Generated by `coregraph review`/);
  });
});

describe("markdownToHtml", () => {
  it("converts h2/h3 headings", () => {
    assert.match(markdownToHtml("## Top\n\n### Sub"), /<h2>Top<\/h2>[\s\S]*<h3>Sub<\/h3>/);
  });

  it("converts tables with header + body rows", () => {
    const md = "| A | B |\n|---|---|\n| 1 | 2 |";
    const html = markdownToHtml(md);
    assert.match(html, /<table>/);
    assert.match(html, /<th>A<\/th>/);
    assert.match(html, /<td>1<\/td>/);
  });

  it("converts bold/italic/code inline", () => {
    const html = markdownToHtml("foo **bold** _italic_ `code`");
    assert.match(html, /<strong>bold<\/strong>/);
    assert.match(html, /<em>italic<\/em>/);
    assert.match(html, /<code>code<\/code>/);
  });

  it("converts list items", () => {
    const html = markdownToHtml("- a\n- b");
    assert.match(html, /<ul><li>a<\/li><li>b<\/li><\/ul>/);
  });

  it("passes through <sub> footer tags", () => {
    const html = markdownToHtml("<sub>footer</sub>");
    assert.match(html, /<sub>footer<\/sub>/);
  });

  it("escapes angle brackets in content", () => {
    const html = markdownToHtml("a <script>evil</script> b");
    assert.doesNotMatch(html, /<script>evil/);
    assert.match(html, /&lt;script&gt;evil&lt;\/script&gt;/);
  });
});
