[package]
name = "coregraph-graph"
version.workspace = true
edition.workspace = true

[dependencies]
coregraph-core = { workspace = true }
serde = { workspace = true }
petgraph = { workspace = true }
bloomfilter = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
lru = { workspace = true }

[dev-dependencies]
tempfile = "3"
