use std::path::Path;

/// 3-stage file inclusion/exclusion pipeline.
/// Stage 1: Known generated/vendored directories
/// Stage 2: Known generated file patterns (extensions, prefixes)
/// Stage 3: GeneratedCodeDetector — content-based heuristics
pub struct FileFilter;

/// Directories that are always excluded.
const EXCLUDED_DIRS: &[&str] = &[
    "node_modules",
    "target",
    ".git",
    "vendor",
    ".gradle",
    ".idea",
    ".vscode",
    "__pycache__",
    ".pytest_cache",
    "dist",
    "build",
    "out",
    ".next",
    ".nuxt",
    "coverage",
];

/// File extensions considered generated or binary (not source).
const EXCLUDED_EXTENSIONS: &[&str] = &[
    "pb.rs", // protobuf generated
    "pb.go",
    "pb.cc",
    "pb.h",
    "grpc.pb.go",
    "min.js",
    "min.css",
    "map", // .js.map, .css.map
];

/// File name suffixes/patterns considered generated.
const GENERATED_MARKERS: &[&str] = &[
    ".generated.",
    ".gen.",
    "_generated.",
    "_gen.",
    ".mock.",
    "_mock.",
];

impl FileFilter {
    /// Returns `true` if the file at `path` should be included in analysis.
    pub fn include(path: &Path) -> bool {
        // Stage 1: directory exclusion
        for component in path.components() {
            if let Some(name) = component.as_os_str().to_str() {
                if EXCLUDED_DIRS.contains(&name) {
                    return false;
                }
            }
        }

        // Stage 2: extension / suffix exclusion
        if let Some(file_name) = path.file_name().and_then(|n| n.to_str()) {
            let lower = file_name.to_lowercase();

            for ext in EXCLUDED_EXTENSIONS {
                if lower.ends_with(ext) {
                    return false;
                }
            }

            for marker in GENERATED_MARKERS {
                if lower.contains(marker) {
                    return false;
                }
            }
        }

        // Stage 3: content-based heuristic (only for text files we can read cheaply)
        if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
            if matches!(ext, "rs" | "go" | "ts" | "js" | "java" | "kt" | "py")
                && is_generated_content(path)
            {
                return false;
            }
        }

        true
    }
}

/// Peek at the first few lines for common "DO NOT EDIT" markers.
fn is_generated_content(path: &Path) -> bool {
    let Ok(content) = std::fs::read_to_string(path) else {
        return false;
    };

    let header: String = content.chars().take(2048).collect();
    let header_lower = header.to_lowercase();

    for marker in &[
        "do not edit",
        "code generated",
        "generated by",
        "auto-generated",
        "autogenerated",
        "this file is generated",
        "@generated",
    ] {
        if header_lower.contains(marker) {
            return true;
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn excludes_node_modules() {
        let p = PathBuf::from("project/node_modules/lodash/index.js");
        assert!(!FileFilter::include(&p));
    }

    #[test]
    fn excludes_target() {
        let p = PathBuf::from("project/target/debug/build/foo.rs");
        assert!(!FileFilter::include(&p));
    }

    #[test]
    fn excludes_protobuf_generated() {
        let p = PathBuf::from("src/proto/foo.pb.rs");
        assert!(!FileFilter::include(&p));
    }

    #[test]
    fn includes_normal_source() {
        let p = PathBuf::from("src/main.rs");
        assert!(FileFilter::include(&p));
    }

    #[test]
    fn excludes_generated_suffix() {
        let p = PathBuf::from("src/foo.generated.ts");
        assert!(!FileFilter::include(&p));
    }

    #[test]
    fn excludes_mock_file() {
        let p = PathBuf::from("src/service_mock.go");
        assert!(!FileFilter::include(&p));
    }
}
